server:
  port: 8083

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 2

zuul:
  routes:
    server:
      path: /server/**
      serviceId: server
      sensitiveHeaders: *

#设置ribbon超时为一分钟
ribbon:
  ServerListRefreshInterval: 2000
  ReadTimeout: 600000
  ConnectTimeout: 600000
  eureka:
    enabled: true

hystrix:
  command:
    default :
      execution :
        timeout :
          enabled : false
