server:
  port: 8083
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    server:
      path: /server/**
      serviceId: server
      sensitiveHeaders: Cookie,Set-Cookie,Authorization

