server:
  port: 8010
spring:
  application:
    name: server
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.1.102:3306/test?useUnicode=true&characterEncoding=UTF-8&socketTimeout=60000
    userName: root
    password: 1234
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
